### ISSUE TITLE
Disease table will repeatedly re-initialize in certain cases

### ISSUE THREAD

**Issue by jsstevenson** [cancervariants/therapy-normalization#176]
Currently we use the Table `item_count()` method to check if the `disease_concepts` or `disease_metadata` tables are empty, and if they are, we auto repopulate them. However, `item_count` doesn't actually auto-update -- the docs say it refreshes every 6 hours on AWS, probably the same locally? -- meaning if you rebuilt the disease table a few minutes ago and refresh the therapy table, it'll also re-rebuild diseases, too (which adds like 30 minutes). 

A few possibilities:
 * Just `scan()` the metadata table, check that the sources are listed, leave it at that
 * Do a single `scan()` on diseases to verify that it's non-empty and move on
 * Only update disease via a command line flag... or offer a command line flag to suppress updating of other resources

**Comment by korikuzma** [comment]
I like the idea of scanning both tables! 

I'm not sure I'm understanding the last suggestion.. I do like the idea of being able to update disease separately with another flag. Since Hemonc relies on data from disease, I think we should always try to update disease if there is no data. If it's fine to leave out this information, we should at least give a warning that disease data isn't present.

The readme should probably be updated to include the use of disease normalizer data for Hemonc.

**Comment by jsstevenson** [comment]
- [ ] Use a minimal `scan()` instead of `.item_count` to check emptiness
- [ ] suppress_external_updates flag
- [ ] update readme
